name: Rules and Ad Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  update-rules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - repo_path: "global"
        - repo_path: "proxy"
        - repo_path: "ad"

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: SouthAlley/q
        path: q-repo

    - name: Download rules to Surge
      run: |
        mkdir -p q-repo/rule/${{ matrix.repo_path }}/attach
        rule_url=""

        case "${{ matrix.repo_path }}" in
          "ad") rule_url="https://raw.githubusercontent.com/RuCu6/QuanX/main/Rules/MyBlockAds.list" ;;
          *) rule_url="https://raw.githubusercontent.com/SouthAlley/z/main/Surge/StreamingRule/StreamingRule.list" ;;
        esac

        curl -L -o q-repo/rule/${{ matrix.repo_path }}/attach/del.ini "$rule_url"
        


    - name: Edit rules
      run: |
        cd q-repo/rule/${{ matrix.repo_path }}/attach
        for file in del.ini; do
          if [ -f "$file" ]; then
            sed -i 's/, /,/g' "$file"
            sed -i -e 's/host,/DOMAIN,/gi' -e 's/host-suffix,/DOMAIN-SUFFIX,/gi' -e 's/host-keyword,/DOMAIN-KEYWORD,/gi' "$file"
            sed -i -e 's/ip-cidr,/IP-CIDR,/gi' -e 's/ip6-cidr,/IP-CIDR6,/gi' -e 's/user-agent,/USER-AGENT,/g' "$file"
            sed -i -e 's/\([^,]*,[^c]*\),.*/\1/g' "$file"
            sed -i '/IP-CIDR/ {/no-resolve/! s/$/,no-resolve/}; /IP-CIDR6/ {/no-resolve/! s/$/,no-resolve/}' "$file"
            sed -i 's/;//g' "$file"
            sed -i 's/#.*//' "$file"
            sed -i '/^[[:space:]]*$/d' "$file"
          else
            echo "$file not found."
          fi
        done

    - name: Copy custom rules to Surge
      run: |
        custom_rules="q-repo/local/add${{ matrix.repo_path }}.ini"
        destination="q-repo/rule/${{ matrix.repo_path }}/attach/del.ini"

        if [ -f "$custom_rules" ]; then
          if [ -f "$destination" ]; then
            cat "$custom_rules" >> "$destination"
          else
            cp "$custom_rules" "$destination"
          fi
        else
          echo "No custom rules found for ${{ matrix.repo_path }}."
        fi



    - name: Add and commit rules
      run: |
        cd q-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rule/${{ matrix.repo_path }}/attach/*
          git commit -m "Update ${{ matrix.repo_path }} rules"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi
  
