name: global

on:
  workflow_dispatch:
  schedule:
    - cron: '25 */6 * * *'

  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: SouthAlley/q
        path: q-repo
   
    - name: Download file to Surge
      run: |
        mkdir -p q-repo/local
        # 规则
        curl -L -o q-repo/local/Global.list "https://raw.githubusercontent.com/SouthAlley/q/main/rule/global/fin.txt"


    - name: Edit Surge/Rule/
      run: |
        cd q-repo/local
        for file in Global.list; do
          if [ -f "$file" ]; then
            # 删除规则
            sed -i '/^\(PROCESS-NAME\|DOMAIN-KEYWORD\|IP-CIDR\|IP-CIDR6\|IP-ASN\|URL-REGEX\|USER-AGENT\|OR\|AND\),.*$/d' "$file"
            # 删除注释
            sed -i 's/#.*//' "$file"
            # 删除空行
            sed -i '/^[[:space:]]*$/d' "$file"
          else
            echo "$file not found."
          fi
        done


    - name: Copy custom rules
      run: |
       if [ -f "q-repo/local/proxy.list" ]; then
         cat q-repo/local/global.ini >> q-repo/local/Global.list
       else
         cp q-repo/local/global.ini q-repo/local/Global.list
       fi


    - name: Add and Commits
      run: |
        cd q-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add local/* 
          git commit -m "Update"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi
    
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
