name: text
on:
  workflow_dispatch:
    
env:
  TZ: Asia/Shanghai
    

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        continue-on-error: false
        timeout-minutes: 10
        with:
          ref: main
          
      - name: run main
        continue-on-error: false
        timeout-minutes: 20
        run: |
          .\r.cmd rule/cdn
      - name: 提交
        continue-on-error: false
        timeout-minutes: 10
        run: |
          git init
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan main
          git add .
          git commit -m "Last Update at $(date +"%Y-%m-%d %H:%M")"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin main
